name: 测试发布功能

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  test-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 设置较短的超时时间
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 创建测试文件
      run: |
        echo "这是一个测试文件" > test.txt
        echo "用于测试发布功能" >> test.txt
        date >> test.txt
        
    - name: 上传到 Release
      uses: ncipollo/release-action@v1
      with:
        tag: test-release-${{ github.run_number }}
        artifacts: "test.txt"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### 测试发布
          这是一个测试发布，用于验证发布功能是否正常。
          
          **测试信息**
          - 运行编号: ${{ github.run_number }}
          - 运行时间: ${{ github.event.repository.updated_at }}
          - 测试状态: 成功 
