name: Build LEDE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache [...]

      - name: Compile LEDE
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          make -j2 V=s
