name: 编译 LEDE 固件

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: 检查初始空间
      run: |
        echo "======================="
        echo "初始空间使用情况："
        echo "======================="
        df -h

    - name: 设置缓存
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          lede/ccache
          lede/dl
        key: ${{ runner.os }}-lede-${{ hashFiles('.config') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-lede-${{ hashFiles('.config') }}-
          ${{ runner.os }}-lede-

    - name: 清理系统空间
      run: |
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /opt/microsoft
        sudo rm -rf /opt/pipx
        sudo rm -rf /usr/share/swift
        echo "======================="
        echo "清理后空间使用情况："
        echo "======================="
        df -h
        
    - name: 安装依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib \
          gettext genisoimage git gperf help2man intltool libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev \
          libtool llvm ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev jq zstd libzstd-dev

    - name: 设置编译环境
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        # 设置 ccache
        ccache -M 15G
        # 设置编译参数
        echo 'CONFIG_CCACHE=y' >> .config
        echo 'CONFIG_CCACHE_DIR="/tmp/ccache"' >> .config
        echo 'CONFIG_CCACHE_BIN="/usr/bin/ccache"' >> .config
        # 优化编译配置
        echo 'CONFIG_BUILDBOT=y' >> .config
        echo 'CONFIG_SINGLE_IMAGE_FILESYSTEM=y' >> .config
        echo 'CONFIG_TARGET_ROOTFS_SQUASHFS=y' >> .config
        echo 'CONFIG_TARGET_IMAGES_GZIP=y' >> .config
        # 添加内存保护
        echo 'CONFIG_TARGET_OPTIMIZATION="-Os -pipe"' >> .config
        echo 'CONFIG_TARGET_OPTIMIZATION_FOR_SIZE=y' >> .config
        # 更新 feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 显示缓存状态
        if [ "${{ steps.cache.outputs.cache-hit }}" == 'true' ]; then
          echo "使用缓存加速编译"
          ccache -s
        else
          echo "未使用缓存，将创建新的缓存"
        fi
        
    - name: 复制配置文件
      run: |
        cp .config lede/
        
    - name: 编译固件
      run: |
        cd lede
        make defconfig
        # 使用 mian.yml 的编译参数，但添加内存保护
        # 使用 nproc+1 核心，但限制最大内存使用
        # 使用 ulimit 限制内存使用，留出 1GB 给系统
        ulimit -v 5000000  # 限制虚拟内存使用为 5GB，给系统留出 2GB
        make -j$(($(nproc) + 1)) V=s 2>&1 | tee build.log
        if [ $? -ne 0 ]; then
          echo "编译失败，保存错误日志"
          cp build.log ../build_error.log
          exit 1
        fi
        # 编译完成后清理
        make clean
        
    - name: 保存编译日志
      if: always()
      run: |
        if [ -f lede/build.log ]; then
          cp lede/build.log build.log
        fi
        
    - name: 上传编译日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          build.log
          build_error.log
        if-no-files-found: ignore
        
    - name: 上传到 Release
      if: ${{ steps.compile.outcome == 'success' }}
      uses: ncipollo/release-action@v1
      with:
        tag: OpenWrt_nokia_ea0326gmp_${{ github.run_number }}
        artifacts: "lede/bin/targets/**/*.bin"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### 基于 Lean 的 LEDE 源码构建
          **首次使用建议全新刷写**
          
          **基本信息**
          - 管理 IP: 192.168.1.1
          - 用户名: root
          - 密码: password
          - 设备型号: nokia_ea0326gmp
          
          **固件说明**
          - `*-initramfs-kernel.bin`: 完整系统镜像，适合首次刷机或系统恢复
          - `*-squashfs-sysupgrade.bin`: 系统升级包，适合日常更新（保留配置）
          
          **使用建议**
          - 首次刷机：使用 initramfs 版本
          - 系统升级：使用 sysupgrade 版本
          - 系统变砖：使用 initramfs 版本恢复 
