jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate Date
      run: |
        DATE=$(date +'%Y%m%d-%H%M')
        echo "PACKAGED_OUTPUTDATE=$DATE" >> $GITHUB_ENV

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          lede/ccache
          lede/dl
        key: ${{ runner.os }}-lede-cache-${{ hashFiles('feeds.conf.default') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache libncurses-dev [...]

    - name: Prepare build environment
      run: |
        git clone https://github.com/coolsnowwolf/lede.git lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp $GITHUB_WORKSPACE/.config .
        make defconfig

    - name: Compile LEDE (with logging)
      run: |
        cd lede
        while sleep 300; do echo "[$(date)] Compiling..."; done &
        make -j2 V=s
        kill %1

    - name: Upload to Release
      if: success()
      uses: ncipollo/release-action@v1
      with:
        tag: OpenWrt_${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: "lede/bin/targets/**/*.bin"
        token: ${{ secrets.GITHUB_TOKEN }}
