name: Build LEDE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    # --- Step 1: Checkout code ---
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # --- Step 2: Clean disk space ---
    - name: Clean up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /swapfile

    # --- Step 3: Generate Date ---
    - name: Generate Date
      id: date
      run: |
        DATE=$(date +'%Y%m%d-%H%M')
        echo "PACKAGED_OUTPUTDATE=${{ github.run_id }}_$DATE" >> $GITHUB_ENV

    # --- Step 4: Cache dependencies ---
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          lede/ccache
          lede/dl
        key: ${{ runner.os }}-lede-${{ hashFiles('.config') }}-${{ github.sha }}

    # --- Step 5: Install dependencies ---
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib \
          gettext genisoimage git gperf help2man intltool libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev \
          libtool llvm ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev jq zstd libzstd-dev

    # --- Step 6: Prepare build environment ---
    - name: Prepare build environment
      run: |
        git clone https://github.com/coolsnowwolf/lede.git lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp $GITHUB_WORKSPACE/.config .
        make defconfig

    # --- Step 7: Check disk space ---
    - name: Check disk space
      run: df -h

    # --- Step 8: Compile LEDE ---
    - name: Compile LEDE
      id: compile
      run: |
        cd lede
        make clean
        make -j$(nproc) V=s
      continue-on-error: false

    # --- Step 9: Upload to Release ---
    - name: Upload to Release
      if: ${{ steps.compile.outcome == 'success' }}
      uses: ncipollo/release-action@v1
      with:
        tag: OpenWrt_nokia_ea0326gmp_${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: "lede/bin/targets/*/*/*.bin"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### Built from Lean's LEDE source
          **First use recommended to flash fresh**
          
          **Basic Info**
          - Admin IP: 192.168.1.1
          - Username: root
          - Password: password
          - Device: nokia_ea0326gmp
          
          **Notes**
          - Use factory image for first flash
          - Use sysupgrade for updates
          - Backup important data before flashing
          
          **Build Info**
          - Build time: ${{ env.PACKAGED_OUTPUTDATE }}
          - Git commit: ${{ github.sha }}
