name: 编译并发布 Nokia EA0326GMP 固件

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  FIRMWARE_PATH: bin/targets/mediatek/filogic/

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: 检出代码（包含.config）
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: 安装完整编译依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib \
          gettext genisoimage git gperf help2man intltool libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev \
          libtool llvm ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev jq zstd libzstd-dev

    - name: 验证配置文件
      run: |
        if [ ! -f ".config" ]; then
          echo "::error::仓库中缺少.config文件"
          exit 1
        fi
        echo "使用仓库中的.config文件进行编译"

    - name: 准备编译环境
      run: |
        make defconfig
        echo "开始下载源码..."
        make download -j$(nproc)
        find dl -size -1024c -delete

    - name: 编译固件（多线程）
      run: make -j$(nproc)

    - name: 编译固件（单线程回退）
      if: failure()
      run: make -j1 V=s

    - name: 创建GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Nokia EA0326GMP 固件 ${{ github.ref_name }}
        body: |
          ## 基于Lean的LEDE源码构建
          **首次使用建议全新刷写**

          ### 设备信息
          - 管理IP: 192.168.1.1
          - 用户名: root
          - 密码: password
          - 型号: nokia_ea0326gmp
          - 编译日期: ${{ steps.get-date.outputs.date }}

          ### 刷机说明
          1. 进入原厂固件升级页面
          2. 选择下载的固件文件
          3. 等待自动重启完成

          ### 注意事项
          ⚠️ 刷机有风险，请提前备份重要数据
          ⚠️ 确保设备电量充足或连接稳定电源
        draft: false

    - name: 上传固件
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.FIRMWARE_PATH }}/*.bin
        asset_name: nokia_ea0326gmp-${{ github.ref_name }}.bin

    - name: 获取当前日期
      id: get-date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
