name: Nokia EA0326GMP 固件编译 (终极修复版)

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
    - name: 1. 检出代码 (深度克隆)
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: 2. 安装完整依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential ccache git gcc g++ make \
          libncurses5-dev libssl-dev python3 python3-distutils \
          rsync unzip wget cmake pkgconf ack antlr3 gawk \
          gettext genisoimage libelf-dev libfuse-dev libglib2.0-dev \
          libltdl-dev libmpc-dev libmpfr-dev libreadline-dev \
          libtool llvm ninja-build scons squashfs-tools subversion \
          texinfo uglifyjs upx-ucl xmlto xxd zlib1g-dev jq zstd

    - name: 3. 初始化编译环境
      run: |
        mkdir -p dl
        [ -f .config ] || cp configs/ea0326gmp.config .config
        make defconfig
        make tools/install -j$(nproc)
        make toolchain/install -j$(nproc)

    - name: 4. 下载源码
      run: |
        make download -j$(nproc)
        find dl -size -1k -delete

    - name: 5. 分阶段编译
      run: |
        # 阶段1：编译基础包
        make -j$(($(nproc)/2)) package/compile
        
        # 阶段2：最终编译
        if ! make -j$(($(nproc)/2)); then
          echo "::warning::降级到单线程编译..."
          make -j1 V=s
        fi

    - name: 6. 打包成果
      run: |
        mkdir -p artifacts
        cp bin/targets/mediatek/filogic/*.bin artifacts/
        cp bin/targets/mediatek/filogic/*.manifest artifacts/
        [ -f logs/error.log ] && cp logs/error.log artifacts/

    - name: 7. 发布版本
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: ${{ github.ref_name }}
        name: "EA0326GMP-${{ github.ref_name }}"
        body: |
          ### 编译信息
          - 时间: $(date +'%Y-%m-%d %H:%M')
          - 源码: $(git rev-parse --short HEAD)
          
          ### 登录信息
          - IP: 192.168.1.1
          - 账号: root/password
        files: |
          artifacts/*.bin
          artifacts/*.manifest
