name: 编译 LEDE 固件

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: 安装依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib \
          gettext genisoimage git gperf help2man intltool libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev \
          libtool llvm ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev jq zstd libzstd-dev

    - name: 设置编译环境
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: 复制配置文件
      run: |
        cp .config lede/
        
    - name: 编译固件
      run: |
        cd lede
        make defconfig
        make -j$(nproc) V=s
        
    - name: 创建发布版本
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: 发布版本 v${{ github.run_number }}
        body: |
          基于 Lean 的 LEDE 源码构建
          
          首次使用建议全新刷写
          
          基本信息
          
          管理 IP: 192.168.1.1
          用户名: root
          密码: password
          设备型号: nokia_ea0326gmp
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 上传固件到发布版本
      uses: softprops/action-gh-release@v1
      with:
        files: lede/bin/targets/**/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
