name: Build LEDE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Display disk space before checkout
      run: |
        echo "磁盘空间信息 (checkout 前):"
        df -h
        du -sh ~/*

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Display disk space after checkout
      run: |
        echo "磁盘空间信息 (checkout 后):"
        df -h
        du -sh ~/*

    - name: Display disk space before cache restore
      run: |
        echo "磁盘空间信息 (缓存恢复前):"
        df -h
        du -sh ~/*

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          /mnt/lede/ccache
          /mnt/lede/dl
        key: ${{ runner.os }}-lede-${{ hashFiles('.config') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-lede-${{ hashFiles('.config') }}-

    - name: Display disk space after cache restore
      run: |
        echo "磁盘空间信息 (缓存恢复后):"
        df -h
        du -sh ~/*

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler flex gawk gcc-multilib \
          gettext genisoimage git gperf help2man intltool libc6-dev-i386 libelf-dev \
          libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev \
          libtool llvm ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev jq zstd libzstd-dev
        
        # 清理 apt 缓存以节省空间
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Display disk space after dependencies install
      run: |
        echo "磁盘空间信息 (依赖安装后):"
        df -h
        du -sh ~/*

    - name: Prepare build environment on /mnt
      run: |
        # 创建/mnt上的编译目录并设置权限
        sudo mkdir -p /mnt/lede
        sudo chown -R runner:runner /mnt/lede
        
        # 克隆源码到/mnt分区
        git clone https://github.com/coolsnowwolf/lede.git /mnt/lede
        cd /mnt/lede
        
        # 检查目录权限
        echo "检查目录权限:"
        ls -ld /mnt/lede
        
        # 更新feeds并安装
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 复制配置文件
        cp $GITHUB_WORKSPACE/.config .
        
        # 生成默认配置并保存配置日志
        make defconfig 2>&1 | tee defconfig.log
        
        # 检查配置是否成功
        if [ ! -f .config ]; then
          echo "配置文件生成失败!"
          exit 1
        fi

    - name: Display disk space before compilation
      run: |
        echo "磁盘空间信息 (编译前):"
        df -h
        du -sh ~/*
        du -sh /mnt/*

    - name: Compile LEDE with error handling
      id: compile
      run: |
        cd /mnt/lede
        
        # 配置ccache并限制大小
        echo "export USE_CCACHE=1" >> ~/.bashrc
        echo "export CCACHE_MAXSIZE=150M" >> ~/.bashrc
        echo "export CCACHE_DIR=$(pwd)/ccache" >> ~/.bashrc
        source ~/.bashrc
        ccache -z
        
        # 将临时文件目录指向/mnt
        mkdir -p /mnt/temp
        export TMPDIR=/mnt/temp
        
        # 创建编译日志目录
        mkdir -p $GITHUB_WORKSPACE/build_logs
        
        # 执行编译并保存详细日志
        echo "开始编译..."
        make -j$(nproc) V=s 2>&1 | tee $GITHUB_WORKSPACE/build_logs/full_compile.log
        
        # 检查编译状态
        if [ $? -ne 0 ]; then
          echo "编译失败，尝试使用单线程继续..."
          
          # 保存失败日志
          cp $GITHUB_WORKSPACE/build_logs/full_compile.log $GITHUB_WORKSPACE/build_logs/failed_compile.log
          
          # 清理临时文件
          find . -name "*.o" -exec rm -f {} \;
          find . -name "*.d" -exec rm -f {} \;
          
          # 使用单线程继续编译
          make -j1 V=s 2>&1 | tee $GITHUB_WORKSPACE/build_logs/resumed_compile.log
          
          # 再次检查编译状态
          if [ $? -ne 0 ]; then
            echo "编译仍然失败，保存错误日志..."
            cp $GITHUB_WORKSPACE/build_logs/resumed_compile.log $GITHUB_WORKSPACE/build_logs/final_failure.log
            
            # 收集错误信息
            echo "最后100行错误日志:"
            tail -n 100 $GITHUB_WORKSPACE/build_logs/final_failure.log
            
            exit 1
          fi
        fi
        
        # 清理非必要文件，但保留配置和依赖信息
        make clean
        
        # 创建最终输出目录
        mkdir -p $GITHUB_WORKSPACE/firmware
        
        # 复制固件文件到工作区
        cp bin/targets/*/*/*.bin $GITHUB_WORKSPACE/firmware/ || true
        cp bin/targets/*/*/*.img.gz $GITHUB_WORKSPACE/firmware/ || true
        
        # 显示ccache统计信息和磁盘使用情况
        ccache -s

    - name: Display disk space after compilation
      run: |
        echo "磁盘空间信息 (编译后):"
        df -h
        du -sh ~/*
        du -sh /mnt/*

    - name: Collect firmware files
      if: success() || failure()
      run: |
        echo "收集固件文件..."
        ls -la $GITHUB_WORKSPACE/firmware/
        echo "固件文件数量: $(ls $GITHUB_WORKSPACE/firmware/ | wc -l)"
        
        # 检查是否有固件文件
        if [ ! "$(ls -A $GITHUB_WORKSPACE/firmware/)" ]; then
          echo "警告: 未找到固件文件!"
        fi

    - name: Upload build logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: $GITHUB_WORKSPACE/build_logs/
        retention-days: 7

    - name: Display disk space before creating PR
      run: |
        echo "磁盘空间信息 (创建PR前):"
        df -h
        du -sh ~/*

    - name: Create Pull Request with changes
      if: ${{ steps.compile.outcome == 'success' }}
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-firmware
        title: "Update firmware binaries"
        body: |
          自动更新固件二进制文件
          构建版本: ${{ env.PACKAGED_OUTPUTDATE }}
        commit-message: "Update firmware: ${{ env.PACKAGED_OUTPUTDATE }}"
        path: firmware/

    - name: Display disk space after build
      if: always()
      run: |
        echo "磁盘空间信息 (构建完成后):"
        df -h
        du -sh ~/*
